name: Lint

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

permissions:
  contents: read
  pull-requests: write 

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: '--ext vue --ext js --ext ts --ext json .'
          reporter: github-pr-review
          fail_on_error: true
